---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: p-worker
spec:
  selector:
    matchLabels:
      app: p-worker
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: p-worker
        tier: backend
        track: stable
    spec:
      containers:
      - name: app-progressive-worker
        image: gcr.io/hsl-gcp-prd-app-buzzwk-prj-spk/flexydial-app
        imagePullPolicy: Always
        command: ["python"]
        args: ["manage.py", "progressive_worker"]
        env:
        - name: FLEXYDIAL_DB_HOST
          value: 10.34.70.2
        - name: FLEXYDIAL_DB_PASS
          value: dxt5qF1bqN2ynMAg
        - name: CRM_DB_HOST
          value: 10.34.70.2
        - name: CRM_DB_PASS
          value: dxt5qF1bqN2ynMAg
        - name: REDIS_HOST
          value: 10.34.71.6
        - name: REDIS_PORT
          value: "6379"
        - name: FREESWITCH_HOST
          value: telephony
        - name: DEBUG
          value: "False"
        - name: GS_BUCKET_NAME
          value: flexydial-storage
        - name: RABBITMQ_HOST
          value: rabbitmq
