# pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gke-phonebook-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: standard
